dist: trusty
sudo: required

branches:
  only:
  - master
  - develop

addons:
  sonarcloud:
    organization: "artemtereshkovich-github"
    token:
      secure: ${SONAR_TOKEN}

services:
  - docker

before_script:
  - docker build -t host-ocean/integration-test -f ./HostOcean/HostOcean.Tests/HostOcean.IntegrationTests/Dockerfile .

script:
  - docker run host-ocean/integration-test
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'