sudo: required

branches:
  only:
  - master
  - develop
  - /^feature|environment/

services:
  - docker

before_script:
  - docker build -t host-ocean/integration-test ./src/HostOcean/HostOcean.Tests/HostOcean.IntegrationTests

script:
  - docker run host-ocean/integration-test