version: '3.4'

services:
  hostocean.api:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__MSSQLDatabaseConnectionString=Server=data.sql;Database=HostOceanDb;User=sa;Password=hostoceandpassword650502!    
    ports:
      - 80:80

  data.sql:
    environment:
      - SA_PASSWORD=hostoceandpassword650502!
      - ACCEPT_EULA=Y
    ports:
      - 5433:1433