version: '3.4'

services:
  hostocean.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44324
      - ConnectionStrings__MSSQLDatabaseConnectionString=Server=data.sql;Database=HostOceanDB;User=sa;Password=hstn650502!
    ports:
      - "51341:80"
      - "44324:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  data.sql:
    environment:
      - SA_PASSWORD=hstn650502!
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"